require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe SharedsController do

  # This should return the minimal set of attributes required to create a valid
  # Shared. As you add validations to Shared, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "device_id" => "1" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # SharedsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all shareds as @shareds" do
      shared = Shared.create! valid_attributes
      get :index, {}, valid_session
      assigns(:shareds).should eq([shared])
    end
  end

  describe "GET show" do
    it "assigns the requested shared as @shared" do
      shared = Shared.create! valid_attributes
      get :show, {:id => shared.to_param}, valid_session
      assigns(:shared).should eq(shared)
    end
  end

  describe "GET new" do
    it "assigns a new shared as @shared" do
      get :new, {}, valid_session
      assigns(:shared).should be_a_new(Shared)
    end
  end

  describe "GET edit" do
    it "assigns the requested shared as @shared" do
      shared = Shared.create! valid_attributes
      get :edit, {:id => shared.to_param}, valid_session
      assigns(:shared).should eq(shared)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Shared" do
        expect {
          post :create, {:shared => valid_attributes}, valid_session
        }.to change(Shared, :count).by(1)
      end

      it "assigns a newly created shared as @shared" do
        post :create, {:shared => valid_attributes}, valid_session
        assigns(:shared).should be_a(Shared)
        assigns(:shared).should be_persisted
      end

      it "redirects to the created shared" do
        post :create, {:shared => valid_attributes}, valid_session
        response.should redirect_to(Shared.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved shared as @shared" do
        # Trigger the behavior that occurs when invalid params are submitted
        Shared.any_instance.stub(:save).and_return(false)
        post :create, {:shared => { "device_id" => "invalid value" }}, valid_session
        assigns(:shared).should be_a_new(Shared)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Shared.any_instance.stub(:save).and_return(false)
        post :create, {:shared => { "device_id" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested shared" do
        shared = Shared.create! valid_attributes
        # Assuming there are no other shareds in the database, this
        # specifies that the Shared created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Shared.any_instance.should_receive(:update).with({ "device_id" => "1" })
        put :update, {:id => shared.to_param, :shared => { "device_id" => "1" }}, valid_session
      end

      it "assigns the requested shared as @shared" do
        shared = Shared.create! valid_attributes
        put :update, {:id => shared.to_param, :shared => valid_attributes}, valid_session
        assigns(:shared).should eq(shared)
      end

      it "redirects to the shared" do
        shared = Shared.create! valid_attributes
        put :update, {:id => shared.to_param, :shared => valid_attributes}, valid_session
        response.should redirect_to(shared)
      end
    end

    describe "with invalid params" do
      it "assigns the shared as @shared" do
        shared = Shared.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Shared.any_instance.stub(:save).and_return(false)
        put :update, {:id => shared.to_param, :shared => { "device_id" => "invalid value" }}, valid_session
        assigns(:shared).should eq(shared)
      end

      it "re-renders the 'edit' template" do
        shared = Shared.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Shared.any_instance.stub(:save).and_return(false)
        put :update, {:id => shared.to_param, :shared => { "device_id" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested shared" do
      shared = Shared.create! valid_attributes
      expect {
        delete :destroy, {:id => shared.to_param}, valid_session
      }.to change(Shared, :count).by(-1)
    end

    it "redirects to the shareds list" do
      shared = Shared.create! valid_attributes
      delete :destroy, {:id => shared.to_param}, valid_session
      response.should redirect_to(shareds_url)
    end
  end

end
